name: Chrome
on: push
jobs:
  test:
    name: Run Cypress tests
    runs-on: ubuntu-latest

    steps:
      # ... other steps ...

      - name: Run Cypress tests
        run: npm run cy:run -- --browser chrome
